version: '3'
services:
  zookeeper:
    image: debezium/zookeeper
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
    volumes:
     - zookeeper-data:/zookeeper/data
     - zookeeper-txns:/zookeeper/txns
     - zookeeper-logs:/zookeeper/logs
     - zookeeper-conf:/zookeeper/conf

  kafka:
    image: debezium/kafka
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
    volumes:
     - kafka-data:/kafka/data
     - kafka-logs:/kafka/logs
     - kafka-config:/kafka/config

  connect:
    image: debezium/connect
    ports:
     - 8083:8083
    links:
     - kafka
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
    volumes:
     - kafka-data:/kafka/data
     - kafka-logs:/kafka/logs
     - kafka-config:/kafka/config

volumes:
  kafka-data:
  kafka-logs:
  kafka-config:
  zookeeper-data:
  zookeeper-txns:
  zookeeper-logs:
  zookeeper-conf:
